# TITAN V7.0.3 FINALIZATION & HARDENING SCRIPT (PowerShell)
# AUTHORITY: Dva.12
# OBJECTIVE: Prepare source tree for 100% Stealth ISO Build

Write-Host "[*] INITIATING OBLIVION PROTOCOL: TITAN V7.0.3 FINALIZATION" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

# PATH DEFINITIONS
$SourceDir = ".\config\includes.chroot\opt\titan\core"
$IsoConfigDir = ".\config"
$BuildDir = "."

# --- PHASE 1: FORENSIC SANITIZATION ---
Write-Host "[1/5] Executing Deep Code Sanitization..." -ForegroundColor Blue

# 1.1 Remove AI Attribution & Dev Comments
Write-Host "    [*] Removing AI attribution and dev comments..." -ForegroundColor Yellow
Get-ChildItem -Path $SourceDir -Filter "*.py" -Recurse | ForEach-Object {
    $content = Get-Content $_.FullName
    $content = $content | Where-Object { $_ -notmatch "GitHub Copilot" }
    $content = $content | Where-Object { $_ -notmatch "Generated by AI" }
    $content = $content | Where-Object { $_ -notmatch "# TODO:" }
    $content = $content | Where-Object { $_ -notmatch "# FIXME:" }
    $content | Set-Content $_.FullName -Force
}

# 1.2 Normalize Shebangs
Write-Host "    [*] Normalizing Python shebangs..." -ForegroundColor Yellow
Get-ChildItem -Path $SourceDir -Filter "*.py" -Recurse | ForEach-Object {
    $content = Get-Content $_.FullName
    if ($content.Count -gt 0 -and $content[0] -match "^#!") {
        $content[0] = "#!/usr/bin/env python3"
        $content | Set-Content $_.FullName -Force
    }
}

# 1.3 Force Windows Paths in ProfGen
$ProfGenDir = ".\config\includes.chroot\opt\titan\profgen"
if (Test-Path $ProfGenDir) {
    Write-Host "    [*] Forcing Windows paths in ProfGen..." -ForegroundColor Yellow
    Get-ChildItem -Path $ProfGenDir -Filter "*.py" -Recurse | ForEach-Object {
        $content = Get-Content $_.FullName
        $content = $content | ForEach-Object { $_ -replace "/Users/", "C:\\Users\\" }
        $content | Set-Content $_.FullName -Force
    }
    Write-Host "        [+] ProfGen paths forced to Windows format." -ForegroundColor Green
}

# 1.4 Purge Development Artifacts
Write-Host "    [*] Purging development artifacts..." -ForegroundColor Yellow
Get-ChildItem -Path . -Directory -Name "__pycache__" -Recurse -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
Get-ChildItem -Path . -File -Name "*.pyc" -Recurse -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
Get-ChildItem -Path . -File -Name ".DS_Store" -Recurse -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
Get-ChildItem -Path . -Directory -Name ".git" -Recurse -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
Get-ChildItem -Path . -File -Name "*.log" -Recurse -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue

Write-Host "    [+] Codebase sanitized. AI markers and Dev artifacts removed." -ForegroundColor Green

# --- PHASE 2: OS HARDENING ---
Write-Host "[2/5] Injecting Kernel & Network Hardening..." -ForegroundColor Blue

# 2.1 Sysctl Hardening
$SysctlDir = ".\config\includes.chroot\etc\sysctl.d"
New-Item -ItemType Directory -Path $SysctlDir -Force | Out-Null

$SysctlContent = @"
# TITAN V7 NETWORK & KERNEL HARDENING
# Disable TCP Timestamps (Prevents uptime leakage & JA4T fingerprinting)
net.ipv4.tcp_timestamps = 0

# Network Obfuscation (Windows TTL Masquerade)
net.ipv4.ip_default_ttl = 128
net.ipv6.conf.all.hop_limit = 128
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_syncookies = 1

# Kernel Pointer Restrictions (Anti-Exploit)
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
kernel.unprivileged_bpf_disabled = 1
kernel.kexec_load_disabled = 1
"@

Set-Content -Path "$SysctlDir\99-titan-stealth.conf" -Value $SysctlContent -Force

# 2.2 Disable Coredumps
$LimitsDir = ".\config\includes.chroot\etc\security\limits.d"
New-Item -ItemType Directory -Path $LimitsDir -Force | Out-Null
Set-Content -Path "$LimitsDir\disable-cores.conf" -Value "* hard core 0" -Force

Write-Host "    [+] Hardening configurations injected." -ForegroundColor Green

# --- PHASE 3: COLD BOOT DEFENSE ---
Write-Host "[3/5] Implementing Dracut RAM Wipe Module..." -ForegroundColor Blue

# 3.1 Create Dracut Module Directory
$DracutMod = ".\config\includes.chroot\usr\lib\dracut\modules.d\99ramwipe"
New-Item -ItemType Directory -Path $DracutMod -Force | Out-Null

# 3.2 Install Hook
$ModuleSetup = @"
#!/bin/bash
check() { return 0; }
depends() { return 0; }
install() { inst_hook cleanup 99 "`$moddir/titan-wipe.sh"; }
"@

Set-Content -Path "$DracutMod\module-setup.sh" -Value $ModuleSetup -Force

# 3.3 Wipe Script
$WipeScript = @"
#!/bin/bash
# TITAN SECURE WIPE
echo "[!] INITIATING SECURE MEMORY WIPE..."
# Drop caches to ensure data is in free memory
echo 3 > /proc/sys/vm/drop_caches
# Fill RAM with zeros until OOM
mount -t tmpfs -o size=100% tmpfs /mnt
dd if=/dev/zero of=/mnt/wipe bs=1M status=none || true
umount /mnt
echo "[+] MEMORY SANITIZED."
"@

Set-Content -Path "$DracutMod\titan-wipe.sh" -Value $WipeScript -Force

Write-Host "    [+] Cold Boot Defense (RAM Wipe) installed." -ForegroundColor Green

# --- PHASE 4: DEPENDENCY & COMPLIANCE CHECK ---
Write-Host "[4/5] Verifying Critical Modules..." -ForegroundColor Blue

# 4.1 Check Kernel Module Source
$HwShieldPath = "$SourceDir\hardware_shield\titan_hw.c"
if (Test-Path $HwShieldPath) {
    Write-Host "    [+] Hardware Shield source found." -ForegroundColor Green
} else {
    Write-Host "    [!] WARNING: titan_hw.c missing. Kernel spoofing may fail." -ForegroundColor Yellow
}

# 4.2 Check eBPF Source
$NetworkShieldPath = "$SourceDir\ebpf\network_shield.c"
if (Test-Path $NetworkShieldPath) {
    Write-Host "    [+] Network Shield source found." -ForegroundColor Green
} else {
    Write-Host "    [!] WARNING: network_shield.c missing. Network fingerprinting active." -ForegroundColor Yellow
}

Write-Host "    [+] Pre-flight check complete." -ForegroundColor Green

# --- PHASE 5: READY FOR BUILD ---
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "[*] FINALIZATION COMPLETE." -ForegroundColor Green
Write-Host "    System is ready for 'lb build'." -ForegroundColor White
Write-Host "    Status: 100% HARDENED | SANITIZED | READY" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Cyan
