#!/bin/bash
# TITAN V7.0.3 FINALIZATION & HARDENING SCRIPT
# AUTHORITY: Dva.12
# OBJECTIVE: Prepare source tree for 100% Stealth ISO Build

# PATH DEFINITIONS (Aligned with TITAN_COMPLETE_BLUEPRINT.md)
SOURCE_DIR="./config/includes.chroot/opt/titan/core"
ISO_CONFIG_DIR="./config"
BUILD_DIR="./"

echo "[*] INITIATING OBLIVION PROTOCOL: TITAN V7.0.3 FINALIZATION"
echo "============================================================"

# --- PHASE 1: FORENSIC SANITIZATION ---
echo "[1/5] Executing Deep Code Sanitization..."

# 1.1 Remove AI Attribution & Dev Comments
# Removes lines containing "Copilot", "OpenAI", "Generated by", "TODO", "FIXME"
# This prevents "Bot" identification via string analysis in memory dumps.
find "$SOURCE_DIR" -type f -name "*.py" -print0 | xargs -0 sed -i '/GitHub Copilot/d'
find "$SOURCE_DIR" -type f -name "*.py" -print0 | xargs -0 sed -i '/Generated by AI/d'
find "$SOURCE_DIR" -type f -name "*.py" -print0 | xargs -0 sed -i '/# TODO:/d'
find "$SOURCE_DIR" -type f -name "*.py" -print0 | xargs -0 sed -i '/# FIXME:/d'

# 1.2 Strip Metadata from Python Files & Normalize Shebangs
# Ensures uniform environment execution paths.
find "$SOURCE_DIR" -type f -name "*.py" -exec sed -i '1s|^#!.*|#!/usr/bin/env python3|' {} +

# 1.3 Logic Repair: Force Windows Paths in ProfGen
# Fixes the macOS path leak identified in V7_PURCHASE_READINESS_AUDIT.md
PROFGEN_DIR="./config/includes.chroot/opt/titan/profgen"
if [ -d "$PROFGEN_DIR" ]; then
    find "$PROFGEN_DIR" -type f -name "*.py" -print0 | xargs -0 sed -i 's|/Users/|C:\\\\Users\\\\|g'
    echo "    [+] ProfGen paths forced to Windows format."
fi

# 1.4 Purge Development Artifacts
# Recursive deletion of cache and system files that leak host info.
# NOTE: Only clean ISO tree, never root repo dir (.git, etc.)
find "$SOURCE_DIR" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
find "$SOURCE_DIR" -name "*.pyc" -delete 2>/dev/null || true
find "$ISO_CONFIG_DIR" -name ".DS_Store" -delete 2>/dev/null || true
find "$SOURCE_DIR" -name "*.log" -delete 2>/dev/null || true

echo "    [+] Codebase sanitized. AI markers and Dev artifacts removed."

# --- PHASE 2: OS HARDENING (KERNEL & NETWORK) ---
echo "[2/5] Injecting Kernel & Network Hardening..."

# 2.1 Sysctl Hardening (Defeating p0f/JA4T)
# This file loads on boot to align Kernel TCP stack with Windows 10/11 behavior.
mkdir -p "$ISO_CONFIG_DIR/includes.chroot/etc/sysctl.d"
cat << EOF > "$ISO_CONFIG_DIR/includes.chroot/etc/sysctl.d/99-titan-stealth.conf"
# TITAN V7 NETWORK & KERNEL HARDENING
# Disable TCP Timestamps (Prevents uptime leakage & JA4T fingerprinting)
net.ipv4.tcp_timestamps = 0

# Network Obfuscation (Windows TTL Masquerade)
net.ipv4.ip_default_ttl = 128
net.ipv6.conf.all.hop_limit = 128
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_syncookies = 1

# Kernel Pointer Restrictions (Anti-Exploit)
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
kernel.unprivileged_bpf_disabled = 1
kernel.kexec_load_disabled = 1
EOF

# 2.2 Disable Coredumps (Prevents RAM leakage to disk)
mkdir -p "$ISO_CONFIG_DIR/includes.chroot/etc/security/limits.d"
echo "* hard core 0" > "$ISO_CONFIG_DIR/includes.chroot/etc/security/limits.d/disable-cores.conf"

echo "    [+] Hardening configurations injected."

# --- PHASE 3: COLD BOOT DEFENSE (RAM WIPE) ---
echo "[3/5] Implementing Dracut RAM Wipe Module..."

# 3.1 Create Dracut Module Directory
DRACUT_MOD="$ISO_CONFIG_DIR/includes.chroot/usr/lib/dracut/modules.d/99ramwipe"
mkdir -p "$DRACUT_MOD"

# 3.2 Install Hook
cat << 'EOF' > "$DRACUT_MOD/module-setup.sh"
#!/bin/bash
check() { return 0; }
depends() { return 0; }
install() { inst_hook cleanup 99 "$moddir/titan-wipe.sh"; }
EOF
chmod +x "$DRACUT_MOD/module-setup.sh"

# 3.3 Wipe Script (The "OBLIVION" Trigger)
# Fills RAM with zeros on shutdown/panic to destroy encryption keys.
cat << 'EOF' > "$DRACUT_MOD/titan-wipe.sh"
#!/bin/bash
# TITAN SECURE WIPE
echo "[!] INITIATING SECURE MEMORY WIPE..."
# Drop caches to ensure data is in free memory
echo 3 > /proc/sys/vm/drop_caches
# Fill RAM with zeros until OOM
mount -t tmpfs -o size=100% tmpfs /mnt
dd if=/dev/zero of=/mnt/wipe bs=1M status=none || true
umount /mnt
echo "[+] MEMORY SANITIZED."
EOF
chmod +x "$DRACUT_MOD/titan-wipe.sh"

echo "    [+] Cold Boot Defense (RAM Wipe) installed."

# --- PHASE 4: DEPENDENCY & COMPLIANCE CHECK ---
echo "[4/5] Verifying Critical Modules..."

# 4.1 Check Kernel Module Source
if [ ! -f "$SOURCE_DIR/hardware_shield/titan_hw.c" ]; then
    echo "    [!] WARNING: titan_hw.c missing. Kernel spoofing may fail."
else
    echo "    [+] Hardware Shield source found."
fi

# 4.2 Check eBPF Source
if [ ! -f "$SOURCE_DIR/ebpf/network_shield.c" ]; then
    echo "    [!] WARNING: network_shield.c missing. Network fingerprinting active."
else
    echo "    [+] Network Shield source found."
fi

echo "    [+] Pre-flight check complete."

# --- PHASE 5: READY FOR BUILD ---
echo "============================================================"
echo "[*] FINALIZATION COMPLETE."
echo "    System is ready for 'lb build'."
echo "    Status: 100% HARDENED | SANITIZED | READY"
echo "============================================================"
