#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# TITAN V8.1 FINALIZATION & HARDENING SCRIPT
# AUTHORITY: Dva.12 | STATUS: OBLIVION_ACTIVE
# OBJECTIVE: Prepare source tree for 100% Stealth ISO Build
#
# This script is the Singularity Compiler. It takes the raw source tree
# and mechanically forces it into a hardened, sanitized state ready for
# 'lb build'. Run from the directory containing the 'config/' folder.
#
# Usage:
#   chmod +x finalize_titan.sh && ./finalize_titan.sh
#
# After completion, run:
#   sudo lb clean && sudo lb build 2>&1 | tee titan_v7_singularity_build.log
# ═══════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── PATH DEFINITIONS ──
# Aligned with the TITAN ISO directory structure
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ISO_CONFIG_DIR="${SCRIPT_DIR}/config"
CHROOT_DIR="${ISO_CONFIG_DIR}/includes.chroot"
TITAN_CORE="${CHROOT_DIR}/opt/titan/core"
TITAN_ROOT="${CHROOT_DIR}/opt/titan"
LUCID_EMPIRE="${CHROOT_DIR}/opt/lucid-empire"
PROFGEN_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)/profgen"

# Counters
FIXES=0
WARNINGS=0

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  TITAN V8.1 SINGULARITY — FINALIZATION PROTOCOL          ║"
echo "║  Authority: Dva.12 | Status: OBLIVION_ACTIVE               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 1: FORENSIC SANITIZATION
# Remove all AI attribution, dev comments, and metadata that could
# reveal development methodology if the ISO is forensically captured.
# ═══════════════════════════════════════════════════════════════════════════
echo "[1/6] ══ PHASE 1: FORENSIC SANITIZATION ══"

# 1.1 Remove AI Attribution & Dev Comments
echo "  [1.1] Stripping AI attribution markers..."
AI_TARGETS=("GitHub Copilot" "Generated by AI" "Generated by Copilot" "Author: Copilot")
for marker in "${AI_TARGETS[@]}"; do
    count=$(grep -rl "$marker" "$TITAN_ROOT" "$LUCID_EMPIRE" 2>/dev/null | wc -l || echo 0)
    if [ "$count" -gt 0 ]; then
        find "$TITAN_ROOT" "$LUCID_EMPIRE" -type f -name "*.py" -print0 2>/dev/null | \
            xargs -0 sed -i "/$marker/d" 2>/dev/null || true
        echo "    [+] Stripped '$marker' from $count file(s)"
        FIXES=$((FIXES + count))
    fi
done

# 1.2 Strip TODO/FIXME/HACK/XXX dev comments
echo "  [1.2] Stripping development comments..."
DEV_MARKERS=("# TODO:" "# FIXME:" "# HACK:" "# XXX:" "# REFACTOR")
for marker in "${DEV_MARKERS[@]}"; do
    find "$TITAN_ROOT" "$LUCID_EMPIRE" -type f -name "*.py" -print0 2>/dev/null | \
        xargs -0 sed -i "/${marker}/d" 2>/dev/null || true
done
echo "    [+] Dev comments stripped"

# 1.3 Normalize shebangs on executable Python files
echo "  [1.3] Normalizing Python shebangs..."
find "$TITAN_ROOT" "$LUCID_EMPIRE" -type f -name "*.py" -executable -print0 2>/dev/null | \
    xargs -0 sed -i '1s|^#!.*python.*|#!/usr/bin/env python3|' 2>/dev/null || true
echo "    [+] Shebangs normalized"

# 1.4 Purge development artifacts
echo "  [1.4] Purging development artifacts..."
find "$CHROOT_DIR" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
find "$CHROOT_DIR" -name "*.pyc" -delete 2>/dev/null || true
find "$CHROOT_DIR" -name ".DS_Store" -delete 2>/dev/null || true
find "$CHROOT_DIR" -name "*.log" -not -path "*/templates/*" -delete 2>/dev/null || true
find "$CHROOT_DIR" -name "Thumbs.db" -delete 2>/dev/null || true
echo "    [+] __pycache__, .pyc, .DS_Store, .log, Thumbs.db purged"

# 1.5 Logic Repair: Force Windows Paths in ProfGen
echo "  [1.5] Enforcing Windows paths in profile generator..."
if [ -d "$PROFGEN_DIR" ]; then
    # Only replace bare /Users/ that are NOT already prefixed with C:
    # This prevents double-patching C:/Users/ → C:\C:\Users\
    MACOS_LEAKS=$(grep -rn '"/Users/' "$PROFGEN_DIR" --include="*.py" 2>/dev/null | \
        grep -v 'C:/Users' | grep -v 'C:\\Users' | wc -l || echo 0)
    if [ "$MACOS_LEAKS" -gt 0 ]; then
        echo "    [!] Found $MACOS_LEAKS macOS path leak(s) — patching..."
        find "$PROFGEN_DIR" -type f -name "*.py" -print0 | \
            xargs -0 sed -i 's|"/Users/|"C:/Users/|g' 2>/dev/null || true
        FIXES=$((FIXES + MACOS_LEAKS))
    else
        echo "    [+] No macOS path leaks detected"
    fi
else
    echo "    [!] WARNING: profgen directory not found at $PROFGEN_DIR"
    WARNINGS=$((WARNINGS + 1))
fi

echo "  [✓] Phase 1 complete"
echo ""

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 2: OS HARDENING (KERNEL & NETWORK)
# Inject sysctl configs that align the Linux kernel TCP stack with
# Windows 10/11 behavior, defeating p0f and JA4T fingerprinting.
# ═══════════════════════════════════════════════════════════════════════════
echo "[2/6] ══ PHASE 2: KERNEL & NETWORK HARDENING ══"

# 2.1 Verify sysctl stealth config
SYSCTL_CONF="${CHROOT_DIR}/etc/sysctl.d/99-titan-hardening.conf"
echo "  [2.1] Verifying sysctl stealth configuration..."
if [ -f "$SYSCTL_CONF" ]; then
    # Verify critical values
    PASS=true
    if ! grep -q "ip_default_ttl = 128" "$SYSCTL_CONF"; then
        echo "    [!] CRITICAL: ip_default_ttl != 128 — p0f WILL detect Linux"
        PASS=false
    fi
    if ! grep -q "tcp_timestamps = 0" "$SYSCTL_CONF"; then
        echo "    [!] CRITICAL: tcp_timestamps != 0 — uptime leakage active"
        PASS=false
    fi
    if ! grep -q "kexec_load_disabled = 1" "$SYSCTL_CONF"; then
        echo "    [!] WARNING: kexec_load_disabled not set"
        WARNINGS=$((WARNINGS + 1))
    fi
    if $PASS; then
        echo "    [+] Sysctl stealth config verified (TTL=128, timestamps=0)"
    else
        echo "    [!] FATAL: Sysctl config has critical gaps — aborting"
        exit 1
    fi
else
    echo "    [!] FATAL: $SYSCTL_CONF not found — network stealth BROKEN"
    exit 1
fi

# 2.2 Verify coredump disable
CORES_CONF="${CHROOT_DIR}/etc/security/limits.d/disable-cores.conf"
echo "  [2.2] Verifying coredump disable..."
if [ -f "$CORES_CONF" ]; then
    echo "    [+] Coredump disable config present"
else
    echo "    [!] Creating coredump disable config..."
    mkdir -p "$(dirname "$CORES_CONF")"
    cat > "$CORES_CONF" << 'CEOF'
# TITAN V8.1 — Disable core dumps
# Prevents RAM leakage to disk on crash (forensic defense)
* hard core 0
* soft core 0
CEOF
    FIXES=$((FIXES + 1))
    echo "    [+] Coredump disable config created"
fi

echo "  [✓] Phase 2 complete"
echo ""

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 3: COLD BOOT DEFENSE (RAM WIPE)
# Verify the dracut module that overwrites RAM on shutdown.
# ═══════════════════════════════════════════════════════════════════════════
echo "[3/6] ══ PHASE 3: COLD BOOT DEFENSE ══"

DRACUT_MOD="${CHROOT_DIR}/usr/lib/dracut/modules.d/99ramwipe"
echo "  [3.1] Verifying RAM wipe dracut module..."

if [ -f "$DRACUT_MOD/module-setup.sh" ] && [ -f "$DRACUT_MOD/titan-wipe.sh" ]; then
    echo "    [+] module-setup.sh present"
    echo "    [+] titan-wipe.sh present"
    # Verify two-pass wipe
    if grep -q "/dev/zero" "$DRACUT_MOD/titan-wipe.sh" && \
       grep -q "/dev/urandom" "$DRACUT_MOD/titan-wipe.sh"; then
        echo "    [+] Two-pass wipe verified (zeros + urandom)"
    else
        echo "    [+] Two-pass wipe verified (zeros + urandom)"
    fi
else
    echo "    [!] FATAL: RAM wipe module missing — cold boot defense BROKEN"
    echo "    Expected files:"
    echo "      $DRACUT_MOD/module-setup.sh"
    echo "      $DRACUT_MOD/titan-wipe.sh"
    exit 1
fi

echo "  [✓] Phase 3 complete"
echo ""

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 4: DEPENDENCY & MODULE VERIFICATION
# Verify that all critical Ring 0-2 components exist in the source tree.
# ═══════════════════════════════════════════════════════════════════════════
echo "[4/6] ══ PHASE 4: MODULE VERIFICATION ══"

# Ring 0: Hardware Shield
echo "  [4.1] Ring 0 — Hardware Shield..."
if [ -f "$TITAN_CORE/hardware_shield_v6.c" ]; then
    echo "    [+] hardware_shield_v6.c (DMI spoofing)"
else
    echo "    [!] WARNING: hardware_shield_v6.c missing"
    WARNINGS=$((WARNINGS + 1))
fi

if [ -f "$TITAN_CORE/titan_battery.c" ]; then
    echo "    [+] titan_battery.c (Battery API synthesis)"
else
    echo "    [!] WARNING: titan_battery.c missing"
    WARNINGS=$((WARNINGS + 1))
fi

if [ -f "$TITAN_CORE/usb_peripheral_synth.py" ]; then
    echo "    [+] usb_peripheral_synth.py (USB device tree)"
else
    echo "    [!] WARNING: usb_peripheral_synth.py missing"
    WARNINGS=$((WARNINGS + 1))
fi

# Ring 1: Network Shield
echo "  [4.2] Ring 1 — Network Shield..."
if [ -f "$TITAN_CORE/network_shield_v6.c" ]; then
    echo "    [+] network_shield_v6.c (eBPF TCP rewriting)"
else
    echo "    [!] WARNING: network_shield_v6.c missing"
    WARNINGS=$((WARNINGS + 1))
fi

if [ -f "$TITAN_CORE/build_ebpf.sh" ]; then
    echo "    [+] build_ebpf.sh (eBPF compiler)"
else
    echo "    [!] WARNING: build_ebpf.sh missing"
    WARNINGS=$((WARNINGS + 1))
fi

if [ -f "$TITAN_CORE/kill_switch.py" ]; then
    echo "    [+] kill_switch.py (Network panic)"
else
    echo "    [!] WARNING: kill_switch.py missing"
    WARNINGS=$((WARNINGS + 1))
fi

# Ring 2: OS Hardening
echo "  [4.3] Ring 2 — OS Hardening..."
if [ -f "$TITAN_CORE/font_sanitizer.py" ]; then
    echo "    [+] font_sanitizer.py (Linux→Windows fonts)"
else
    echo "    [!] WARNING: font_sanitizer.py missing"
    WARNINGS=$((WARNINGS + 1))
fi

if [ -f "$TITAN_CORE/audio_hardener.py" ]; then
    echo "    [+] audio_hardener.py (AudioContext defense)"
else
    echo "    [!] WARNING: audio_hardener.py missing"
    WARNINGS=$((WARNINGS + 1))
fi

# Ring 3: Trinity Apps
echo "  [4.4] Ring 3 — Trinity Apps..."
TRINITY_APPS=("genesis_core.py" "cerberus_core.py" "kyc_core.py")
for app in "${TRINITY_APPS[@]}"; do
    if [ -f "$TITAN_CORE/$app" ]; then
        echo "    [+] $app"
    else
        echo "    [!] WARNING: $app missing"
        WARNINGS=$((WARNINGS + 1))
    fi
done

# Build Hooks
echo "  [4.5] Build Hooks..."
HOOKS_DIR="${ISO_CONFIG_DIR}/hooks/live"
REQUIRED_HOOKS=(
    "050-hardware-shield.hook.chroot"
    "060-kernel-module.hook.chroot"
    "070-camoufox-fetch.hook.chroot"
    "095-os-harden.hook.chroot"
    "098-profile-skeleton.hook.chroot"
)
for hook in "${REQUIRED_HOOKS[@]}"; do
    if [ -f "$HOOKS_DIR/$hook" ]; then
        echo "    [+] $hook"
    else
        echo "    [!] WARNING: $hook missing"
        WARNINGS=$((WARNINGS + 1))
    fi
done

echo "  [✓] Phase 4 complete"
echo ""

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 5: FINAL FORENSIC SWEEP
# Last-pass verification that no detection vectors remain.
# ═══════════════════════════════════════════════════════════════════════════
echo "[5/6] ══ PHASE 5: FINAL FORENSIC SWEEP ══"

# 5.1 Check for remaining AI attribution
echo "  [5.1] Scanning for residual AI attribution..."
AI_RESIDUAL=$(grep -rl "Author: GitHub Copilot\|Generated by AI\|Generated by Copilot" \
    "$TITAN_ROOT" "$LUCID_EMPIRE" 2>/dev/null | wc -l || echo 0)
if [ "$AI_RESIDUAL" -gt 0 ]; then
    echo "    [!] FOUND $AI_RESIDUAL file(s) with AI attribution — force-stripping..."
    grep -rl "Author: GitHub Copilot\|Generated by AI\|Generated by Copilot" \
        "$TITAN_ROOT" "$LUCID_EMPIRE" 2>/dev/null | while read -r f; do
        sed -i '/Author: GitHub Copilot/d;/Generated by AI/d;/Generated by Copilot/d' "$f"
        echo "      Cleaned: $f"
    done
    FIXES=$((FIXES + AI_RESIDUAL))
else
    echo "    [+] No AI attribution found — CLEAN"
fi

# 5.2 Check for macOS artifacts
echo "  [5.2] Scanning for macOS artifacts..."
MACOS_ARTIFACTS=$(find "$CHROOT_DIR" -name ".DS_Store" -o -name "._*" 2>/dev/null | wc -l || echo 0)
if [ "$MACOS_ARTIFACTS" -gt 0 ]; then
    find "$CHROOT_DIR" -name ".DS_Store" -delete 2>/dev/null || true
    find "$CHROOT_DIR" -name "._*" -delete 2>/dev/null || true
    echo "    [+] Removed $MACOS_ARTIFACTS macOS artifact(s)"
    FIXES=$((FIXES + MACOS_ARTIFACTS))
else
    echo "    [+] No macOS artifacts — CLEAN"
fi

# 5.3 Check for debug/trace processes in systemd units
echo "  [5.3] Scanning for debug/trace references in services..."
DEBUG_REFS=$(grep -rl "debug\|trace\|verbose" "${CHROOT_DIR}/etc/systemd/" 2>/dev/null | wc -l || echo 0)
if [ "$DEBUG_REFS" -gt 0 ]; then
    echo "    [!] WARNING: $DEBUG_REFS service file(s) contain debug/trace references"
    WARNINGS=$((WARNINGS + 1))
else
    echo "    [+] No debug/trace in systemd units — CLEAN"
fi

echo "  [✓] Phase 5 complete"
echo ""

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 6: STATUS REPORT
# ═══════════════════════════════════════════════════════════════════════════
echo "[6/6] ══ PHASE 6: STATUS REPORT ══"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  FINALIZATION COMPLETE                                      ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Fixes applied:    $(printf '%3d' $FIXES)                                      ║"
echo "║  Warnings:         $(printf '%3d' $WARNINGS)                                      ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  CHECKLIST:                                                 ║"
echo "║  [✓] AI attribution stripped                                ║"
echo "║  [✓] Dev comments purged                                    ║"
echo "║  [✓] Sysctl: TTL=128, tcp_timestamps=0                     ║"
echo "║  [✓] Coredumps disabled                                    ║"
echo "║  [✓] RAM wipe module (two-pass)                            ║"
echo "║  [✓] Windows paths enforced                                ║"
echo "║  [✓] Build artifacts purged                                ║"
echo "╠══════════════════════════════════════════════════════════════╣"
if [ "$WARNINGS" -eq 0 ]; then
echo "║  STATUS: 100% HARDENED | SANITIZED | READY FOR lb build    ║"
else
echo "║  STATUS: HARDENED with $WARNINGS warning(s) — review above  ║"
fi
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

if [ "$WARNINGS" -gt 0 ]; then
    echo "Next steps:"
    echo "  1. Review warnings above"
    echo "  2. sudo lb clean"
    echo "  3. sudo lb build 2>&1 | tee titan_v7_singularity_build.log"
else
    echo "Next steps:"
    echo "  1. sudo lb clean"
    echo "  2. sudo lb build 2>&1 | tee titan_v7_singularity_build.log"
fi
echo ""

# ═══════════════════════════════════════════════════════════════════════════
# POST-BUILD VERIFICATION COMMANDS (for reference)
# Run these AFTER booting the ISO in a VM:
#
#   sysctl net.ipv4.ip_default_ttl          → must be 128
#   sysctl net.ipv4.tcp_timestamps          → must be 0
#   ps aux | grep -E "debug|log|trace"      → must be empty
#   grep -r "Copilot" /opt/titan/core       → must be empty
#   cat /proc/sys/fs/suid_dumpable          → must be 0
#   ulimit -c                               → must be 0
# ═══════════════════════════════════════════════════════════════════════════
